import type { Problem } from '../types';

export const BOOLEAN_PROBLEMS = [
  {
    id: 'bool-001',
    source: 'bank',
    topic: 'boolean',
    subtopics: ['self-duality', 'complementary inputs', 'Boolean functions'],
    difficulty: 3,
    title: 'Self-dual Boolean functions',
    statement:
      'Let $n\\ge1$. A Boolean function $f:\\{0,1\\}^n\\to\\{0,1\\}$ is **self-dual** if\n\n$$\nf(1-x_1,\\ldots,1-x_n)=1-f(x_1,\\ldots,x_n)\n$$\n\nfor every input $(x_1,\\ldots,x_n)$. Find, as a function of $n$, the number of self-dual Boolean functions.',
    hints: [
      'Pair each input vector with its bitwise complement.',
      'For $n\\ge1$, no input vector is equal to its complement. How many complementary pairs are there?',
      'Within each pair, choosing the function value on one input forces its value on the other input.',
    ],
    solution:
      'The map\n\n$$\n(x_1,\\ldots,x_n)\\longmapsto(1-x_1,\\ldots,1-x_n)\n$$\n\nis an involution on the $2^n$ input vectors. For $n\\ge1$ it has no fixed point, since a fixed bit would have to satisfy $x_i=1-x_i$. Thus the inputs split into\n\n$$\n\\frac{2^n}{2}=2^{n-1}\n$$\n\nunordered complementary pairs.\n\nFor each pair $\\{x,\\bar x\\}$, choose $f(x)$ freely. There are two choices. Self-duality then forces $f(\\bar x)=1-f(x)$. Choices on distinct pairs are independent, and every such collection of choices defines a self-dual function. Therefore the number of functions is\n\n$$\n2^{2^{n-1}}.\n$$',
    answer: {
      type: 'expression',
      canonical: '2^(2^(n - 1))',
      display: '$2^{2^{n-1}}$',
      nRange: [1, 10],
    },
    estMinutes: 10,
  },
  {
    id: 'bool-002',
    source: 'bank',
    topic: 'boolean',
    subtopics: ['monotone functions', 'antichains', 'Boolean lattice'],
    difficulty: 4,
    title: 'Monotone functions on four variables',
    statement:
      'A Boolean function $f:\\{0,1\\}^4\\to\\{0,1\\}$ is **monotone** if $f(x)\\le f(y)$ whenever $x_i\\le y_i$ for every coordinate $i$. How many monotone Boolean functions of four labelled variables are there?',
    hints: [
      'Identify an input vector with the subset of coordinates where it equals $1$. The true inputs of a monotone function form an up-set.',
      'An up-set is determined by its minimal members, which form an antichain in the Boolean lattice $B_4$. Count these antichains.',
      'After handling $\\varnothing$ and $[4]$, fix the chosen two-element subsets and view them as an edge set $F$ on four vertices. Allowed singletons are isolated vertices; allowed three-element sets correspond to vertices common to every edge.',
      'For nonempty $F$, if $i(F)$ and $c(F)$ are the numbers of isolated and common vertices, there are $2^{i(F)}+2^{c(F)}-1$ completions. Sum these quantities over the nonempty edge sets.',
    ],
    solution:
      'Identify each input with the subset of $[4]$ on which it is $1$. The set of true inputs of a monotone function is an up-set in the Boolean lattice $B_4$. Its minimal members form an antichain. Conversely, an antichain determines the up-set generated by its members. Thus it is enough to count the antichains of $B_4$.\n\nAn antichain containing $\\varnothing$ must be $\\{\\varnothing\\}$, and one containing $[4]$ must be $\\{[4]\\}$. We now count antichains using only levels $1$, $2$, and $3$.\n\nFix the chosen two-element subsets and view them as an edge set $F$ in the complete graph on vertex set $[4]$. First suppose $F$ is empty. Let $A$ be the set of chosen singletons, and index each chosen three-element set as $[4]\\setminus\\{j\\}$ with $j\\in J$. A singleton $\\{i\\}$ and a triple $[4]\\setminus\\{j\\}$ are incomparable exactly when $i=j$. Hence either $A$ or $J$ is empty, or $A=J=\\{i\\}$ for one $i$. This gives\n\n$$\n2^4+2^4-1+4=35\n$$\n\nantichains when $F$ is empty, including the empty antichain.\n\nNow let $F$ be nonempty. Write $i(F)$ for the number of isolated vertices of $F$, and $c(F)$ for the number of vertices common to every edge of $F$. A chosen singleton must be an isolated vertex. A triple $[4]\\setminus\\{j\\}$ is incomparable with every edge exactly when every edge contains $j$, so its index $j$ must be common to every edge. No vertex can be both isolated and common to every edge of nonempty $F$. Therefore the number of completions of $F$ is\n\n$$\n2^{i(F)}+2^{c(F)}-1.\n$$\n\nWe evaluate the two sums separately. Double-count pairs consisting of a nonempty edge set $F$ and a subset of its isolated vertices. If that subset has size $a$, all edges of $F$ must lie on the other $4-a$ vertices. Hence\n\n$$\n\\sum_{\\varnothing\\ne F\\subseteq E(K_4)}2^{i(F)}\n=\\sum_{a=0}^4\\binom4a\\left(2^{\\binom{4-a}{2}}-1\\right)\n=63+28+6=97.\n$$\n\nThere are $63$ nonempty edge sets. Six one-edge sets have $c(F)=2$. There are\n\n$$\n4\\left(\\binom32+\\binom33\\right)=16\n$$\n\nedge sets of size at least two whose edges share one common vertex; these have $c(F)=1$. Every other nonempty edge set has $c(F)=0$. Therefore\n\n$$\n\\sum_{\\varnothing\\ne F\\subseteq E(K_4)}2^{c(F)}\n=63+6(2^2-1)+16(2^1-1)=97.\n$$\n\nThe nonempty choices of $F$ consequently give $97+97-63=131$ antichains. Adding the $35$ with $F$ empty and the two singleton antichains containing an extreme element gives\n\n$$\n131+35+2=168.\n$$\n\nThus there are $168$ monotone Boolean functions of four labelled variables.',
    answer: {
      type: 'numeric',
      canonical: 168,
      display: '$168$',
    },
    related: ['rel-003', 'logic-001'],
    estMinutes: 24,
  },
  {
    id: 'bool-003',
    source: 'bank',
    topic: 'boolean',
    subtopics: ['functional completeness', "Post's criterion", 'connective clones'],
    difficulty: 4,
    title: 'Functionally complete connective sets',
    statement:
      'A set of Boolean connectives is **functionally complete** if formulas using only those connectives can represent every Boolean function. Constants are nullary connectives. Here $x\\uparrow y=\\neg(x\\land y)$ is NAND, $x\\oplus y$ is XOR, and $\\operatorname{maj}(x,y,z)$ is $1$ exactly when at least two inputs are $1$.\n\nSelect exactly the labels of the functionally complete sets.\n\n- **A.** $\\{\\neg,\\land\\}$\n- **B.** $\\{\\to,0\\}$\n- **C.** $\\{\\uparrow\\}$\n- **D.** $\\{\\land,\\lor\\}$\n- **E.** $\\{\\oplus,1\\}$\n- **F.** $\\{\\operatorname{maj},\\neg\\}$',
    hints: [
      'Use Post’s criterion. A complete set cannot be contained in any of the five closed classes: $0$-preserving, $1$-preserving, monotone, affine, or self-dual.',
      'For each labelled set, make five checks. To rule out a set, it is enough to find one class containing every connective in it.',
      'Conjunction and disjunction share several preservation properties. XOR with a constant remains affine. Majority and negation share a duality property.',
      'For any set that survives Post’s test, confirm it by generating negation and conjunction. Reusing the same input of a binary connective can be useful.',
    ],
    solution:
      'Post’s completeness criterion says that a collection of Boolean functions is functionally complete exactly when it is not contained in any of these five classes:\n\n- $T_0$: $0$-preserving functions;\n- $T_1$: $1$-preserving functions;\n- $M$: monotone functions;\n- $L$: affine functions over $\\mathbb F_2$;\n- $S$: self-dual functions.\n\nEach class is closed under composition.\n\n**A is complete.** Negation is not $0$-preserving, $1$-preserving, or monotone. Conjunction is not affine and is not self-dual. Thus A is contained in none of the five classes. Equivalently, disjunction follows from De Morgan’s law, so the usual connectives can be generated.\n\n**B is complete.** It also has a direct construction:\n\n$$\n\\neg x=(x\\to0),\n\\qquad\nx\\lor y=(x\\to y)\\to y.\n$$\n\nNegation and disjunction generate conjunction by De Morgan’s law. In terms of Post’s criterion, implication breaks $T_0$, monotonicity, and affinity, while the constant $0$ breaks $T_1$ and self-duality.\n\n**C is complete.** NAND gives\n\n$$\n\\neg x=x\\uparrow x,\n\\qquad\nx\\land y=(x\\uparrow y)\\uparrow(x\\uparrow y).\n$$\n\nIt therefore generates A. Its truth table also shows that NAND lies outside all five Post classes.\n\n**D is not complete.** Both conjunction and disjunction are monotone. In fact, they are also both $0$-preserving and $1$-preserving. Formulas built from them stay in these classes.\n\n**E is not complete.** XOR and the constant $1$ are affine functions over $\\mathbb F_2$, and compositions of affine functions remain affine. They cannot generate a non-affine function such as conjunction.\n\n**F is not complete.** Majority and negation are both self-dual. Compositions of self-dual functions remain self-dual, so they cannot represent every Boolean function.\n\nHence the functionally complete sets are exactly $\\{A,B,C\\}$.',
    answer: {
      type: 'set',
      canonical: ['A', 'B', 'C'],
      display: '$\\{A,B,C\\}$',
    },
    estMinutes: 20,
  },
] satisfies readonly Problem[];
